version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: isort
    versions:
    - 5.7.0
    - 5.8.0
  - dependency-name: boto3
    versions:
    - 1.16.47
    - 1.16.63
    - 1.17.17
  - dependency-name: pytz
    versions:
    - "2020.5"
    - "2021.1"
  - dependency-name: aws-lambda-powertools
    versions:
    - 1.10.1
    - 1.9.1
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: babel
    versions:
    - 2.9.0
  - dependency-name: interrogate
    versions:
    - 1.3.2
