#   Copyright 2020 Antonin Jousson
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#  http://aws.amazon.com/apache2.0/
#
#  or in the "license" file accompanying this file. This file is
#  distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
#  OF ANY KIND, either express or implied. See the License for the
#  specific language governing permissions and limitations under the
#  License.

import sys
import unittest

from lex_bot_tester.aws.alexa.alexaskilltest import AlexaSkillTest

verbose = True


class StibScheduleTestSuite(AlexaSkillTest):
    def test_commute_preferences_intent(self):
        """
        Test generated by urutu on 2020-03-30 13:40:34
        """
        skill_name = "STIB schedule"
        intent = "CaptureCommutePreferencesIntent"
        conversation = [
            {"slot": None, "text": "open stib schedule ", "prompt": None},
            {
                "slot": "stop_id",
                "text": "one thousand fifty nine",
                "prompt": "At which stop do you start your journey?",
            },
            {
                "slot": "line_id",
                "text": "ninety three",
                "prompt": "Which line do you take?",
            },
        ]
        simulation_result = self.conversation_text(
            skill_name, intent, conversation, verbose=verbose
        )
        # self.assertSimulationResultIsCorrect(simulation_result, verbose=verbose)

    def test_next_tram_intent(self):
        """
        Test generated by urutu on 2020-03-29 11:52:47
        """
        skill_name = "STIB schedule"
        intent = "GetArrivalTimesIntent"
        conversation = [
            {
                "slot": None,
                "text": "ask stib schedule when is the next tram",
                "prompt": None,
            }
        ]
        simulation_result = self.conversation_text(
            skill_name, intent, conversation, verbose=verbose
        )
        # self.assertSimulationResultIsCorrect(simulation_result, verbose=verbose)

    def test_help_intent(self):
        """
        Test generated by urutu on 2020-03-29 11:52:47
        """
        skill_name = "STIB schedule"
        intent = "AMAZON.HelpIntent"
        conversation = [
            {"slot": None, "text": "ask stib schedule help", "prompt": None}
        ]
        simulation_result = self.conversation_text(
            skill_name, intent, conversation, verbose=verbose
        )
        # self.assertSimulationResultIsCorrect(simulation_result, verbose=verbose)


if __name__ == "__main__":
    verbose = "-v" in sys.argv or "--verbose" in sys.argv
    unittest.main()
